<?php

/**
 * This is the model base class for the table "{{crawl_url}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CrawlUrlModel".
 *
 * Columns in table "{{crawl_url}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property string $url
 * @property string $site
 * @property integer $category_id
 * @property string $created_datetime
 * @property string $updated_datetime
 * @property integer $status
 * @property string $avatar_path
 *
 */
abstract class BaseCrawlUrlModel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{crawl_url}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CrawlUrlModel|CrawlUrlModels', $n);
	}

	public static function representingColumn() {
		return 'url';
	}

	public function rules() {
		return array(
			array('url, site', 'required'),
			array('category_id, status', 'numerical', 'integerOnly'=>true),
			array('name, url, site, avatar_path', 'length', 'max'=>255),
			array('created_datetime, updated_datetime', 'safe'),
			array('name, category_id, created_datetime, updated_datetime, status, avatar_path', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, url, site, category_id, created_datetime, updated_datetime, status, avatar_path', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'url' => Yii::t('app', 'Url'),
			'site' => Yii::t('app', 'Site'),
			'category_id' => Yii::t('app', 'Category'),
			'created_datetime' => Yii::t('app', 'Created Datetime'),
			'updated_datetime' => Yii::t('app', 'Updated Datetime'),
			'status' => Yii::t('app', 'Status'),
			'avatar_path' => Yii::t('app', 'Avatar Path'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('site', $this->site, true);
		$criteria->compare('category_id', $this->category_id);
		$criteria->compare('created_datetime', $this->created_datetime, true);
		$criteria->compare('updated_datetime', $this->updated_datetime, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('avatar_path', $this->avatar_path, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}