<?php

/**
 * This is the model base class for the table "football_rank_point".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FootballRankPointModel".
 *
 * Columns in table "football_rank_point" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $Pos
 * @property integer $P
 * @property integer $W
 * @property integer $D
 * @property integer $L
 * @property integer $GF
 * @property integer $GA
 * @property integer $GD
 * @property integer $PTS
 * @property string $ShadeColor
 * @property string $long_name
 * @property string $short_name
 * @property integer $teamid
 * @property integer $league_id
 * @property string $session_league
 * @property string $created_datetime
 * @property string $updated_datetime
 *
 */
abstract class BaseFootballRankPointModel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'football_rank_point';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'FootballRankPointModel|FootballRankPointModels', $n);
	}

	public static function representingColumn() {
		return 'ShadeColor';
	}

	public function rules() {
		return array(
			array('Pos, P, W, D, L, GF, GA, GD, PTS, teamid, league_id', 'numerical', 'integerOnly'=>true),
			array('ShadeColor, long_name, short_name', 'length', 'max'=>20),
			array('session_league', 'length', 'max'=>15),
			array('created_datetime, updated_datetime', 'safe'),
			array('Pos, P, W, D, L, GF, GA, GD, PTS, ShadeColor, long_name, short_name, teamid, league_id, session_league, created_datetime, updated_datetime', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, Pos, P, W, D, L, GF, GA, GD, PTS, ShadeColor, long_name, short_name, teamid, league_id, session_league, created_datetime, updated_datetime', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'Pos' => Yii::t('app', 'Pos'),
			'P' => Yii::t('app', 'P'),
			'W' => Yii::t('app', 'W'),
			'D' => Yii::t('app', 'D'),
			'L' => Yii::t('app', 'L'),
			'GF' => Yii::t('app', 'Gf'),
			'GA' => Yii::t('app', 'Ga'),
			'GD' => Yii::t('app', 'Gd'),
			'PTS' => Yii::t('app', 'Pts'),
			'ShadeColor' => Yii::t('app', 'Shade Color'),
			'long_name' => Yii::t('app', 'Long Name'),
			'short_name' => Yii::t('app', 'Short Name'),
			'teamid' => Yii::t('app', 'Teamid'),
			'league_id' => Yii::t('app', 'League'),
			'session_league' => Yii::t('app', 'Session League'),
			'created_datetime' => Yii::t('app', 'Created Datetime'),
			'updated_datetime' => Yii::t('app', 'Updated Datetime'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('Pos', $this->Pos);
		$criteria->compare('P', $this->P);
		$criteria->compare('W', $this->W);
		$criteria->compare('D', $this->D);
		$criteria->compare('L', $this->L);
		$criteria->compare('GF', $this->GF);
		$criteria->compare('GA', $this->GA);
		$criteria->compare('GD', $this->GD);
		$criteria->compare('PTS', $this->PTS);
		$criteria->compare('ShadeColor', $this->ShadeColor, true);
		$criteria->compare('long_name', $this->long_name, true);
		$criteria->compare('short_name', $this->short_name, true);
		$criteria->compare('teamid', $this->teamid);
		$criteria->compare('league_id', $this->league_id);
		$criteria->compare('session_league', $this->session_league, true);
		$criteria->compare('created_datetime', $this->created_datetime, true);
		$criteria->compare('updated_datetime', $this->updated_datetime, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}