<?php

/**
 * This is the model base class for the table "{{crawl_content}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CrawlContentModel".
 *
 * Columns in table "{{crawl_content}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $url_id
 * @property string $title
 * @property string $url_key
 * @property string $content
 * @property string $avatar_url
 * @property string $from
 * @property string $created_datetime
 * @property string $updated_datetime
 *
 */
abstract class BaseCrawlContentModel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{crawl_content}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CrawlContentModel|CrawlContentModels', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('url_id', 'required'),
			array('url_id', 'numerical', 'integerOnly'=>true),
			array('title, url_key, avatar_url', 'length', 'max'=>255),
			array('from', 'length', 'max'=>100),
			array('content, created_datetime, updated_datetime', 'safe'),
			array('title, url_key, content, avatar_url, from, created_datetime, updated_datetime', 'default', 'setOnEmpty' => true, 'value' => null),
			array('url_id, title, url_key, content, avatar_url, from, created_datetime, updated_datetime', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'url_id' => Yii::t('app', 'Url'),
			'title' => Yii::t('app', 'Title'),
			'url_key' => Yii::t('app', 'Url Key'),
			'content' => Yii::t('app', 'Content'),
			'avatar_url' => Yii::t('app', 'Avatar Url'),
			'from' => Yii::t('app', 'From'),
			'created_datetime' => Yii::t('app', 'Created Datetime'),
			'updated_datetime' => Yii::t('app', 'Updated Datetime'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('url_id', $this->url_id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('url_key', $this->url_key, true);
		$criteria->compare('content', $this->content, true);
		$criteria->compare('avatar_url', $this->avatar_url, true);
		$criteria->compare('from', $this->from, true);
		$criteria->compare('created_datetime', $this->created_datetime, true);
		$criteria->compare('updated_datetime', $this->updated_datetime, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}